# Generated by Django 4.1.7 on 2023-03-14 00:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the city (for example Klaipėda)', max_length=200, verbose_name='City_name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ad title')),
                ('description', models.TextField(max_length=1000, verbose_name='Ad_description')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique ad id', verbose_name='UUID')),
                ('due_ad_end', models.DateField(verbose_name='Expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('t', 'Transportation'), ('r', 'Real estate'), ('w', 'Work, services'), ('f', 'Furniture, appliances'), ('c', 'Computers'), ('o', 'Communication'), ('m', 'Media'), ('e', 'Entertainment'), ('l', 'Clothing'), ('c', 'Children')], default='a', help_text='Category (for example Computers)', max_length=1)),
                ('city', models.ManyToManyField(blank=True, to='bluetrade_app.city')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
    ]
